owner: sodaliterocks
repo: upptime

assignees:
  - astravexton
  - electricduck

sites:
  - name: Sodalite
    url: https://sodalite.rocks

status-website:
  cname: uptime.sodalite.rocks
  name: Sodalite Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/sodaliterocks
    - title: Website
      href: https://sodalite.rocks
  theme: dark
