owner: sodaliterocks
repo: upptime

assignees:
  - astravexton
  - electricduck

sites:
  - name: OSTree Repository
    url: https://ostree.sodalite.rocks
  - name: Git (Gitea)
    url: https://git.sodalite.rocks/gitea
  - name: Git (GitHub)
    url: https://git.sodalite.rocks/github
  - name: Website
    url: https://sodalite.rocks

status-website:
  cname: uptime.sodalite.rocks
  name: Sodalite Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/sodaliterocks
    - title: Website
      href: https://sodalite.rocks
