owner: sodaliterocks
repo: upptime

assignees:
  - astravexton
  - electricduck

sites:
  - name: Sodalite
    url: https://sodalite.rocks

status-website:
  cname: uptime.sodalite.rocks
  name: Sodalite Uptime
  theme: dark
